name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 21098
          # If your new key has NO password, remove the passphrase line below:
          # passphrase: ${{ secrets.SSH_PASSPHRASE }} 
          use_insecure_cipher: true 
          source: "./*"
          target: "/home/sreezmqo/public_html"
          strip_components: 0