name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy Files to Server (SCP)
        uses: appleboy/scp-action@v0.1.7 # Using a stable version
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 21098
          use_insecure_cipher: true # Fixes most EOF/Handshake errors on cPanel
          source: "."
          # Update 'sreeanantha' to your actual folder name if it's different
          target: "/home/sreezmqo/public_html/sreeanantha"

      - name: Execute Remote Commands (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 21098
          script: |
            cd /home/sreezmqo/public_html/sreeanantha
            git pull origin main
            touch passenger_wsgi.py